version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres_database
    ports:
      - "5432:5432"

  redis_stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"


  # redis_server:
  #   image: redis
  #   container_name: redis-server
  #   ports:
  #     - ":6379"


